config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  get 'terms', to: 'tops#terms'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'treatment', to: 'tops#treatment'

  get 'post', to: 'tops#post'

  get 'saikyouni_omoroi_app', to:'tops#saikyouni_omoroi_app'

  get 'prison', to: 'calorie_counter/chats#prison'
  get 'purgatory', to: 'calorie_counter/chats#purgatory'
  get '/path/to/mercy', to: 'calorie_counter/chats#mercy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'

  post 'select_theme', to: 'themes#select'

  namespace :calorie_counter do
    resources :chats
  end

  namespace :pomodoro_timer do
    resources :timers
  end

  namespace :stolen_umbrella do
    resources :umbrellas
  end

  namespace :talk_deck_butler do
    resources :tasks
  end

  get 'escape', to: 'escape/homes#top'
  namespace :escape do
    resources :homes
    resources :sns
    resources :rooms
    resources :endroles
  end

  namespace :aespa do
    resources :songs, only: [:index, :show], param: :title do
      collection do
        get 'aespa_no_1'
      end
    end
  end

  resources :users
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :song_tags, dependent: :destroy
  has_many :tags, through: :song_tags

  validates :title, presence: true
  validates :body, presence: true

  def self.select_song(tag_titles)
    selected_tag_ids = Tag.where(title: tag_titles).pluck(:id) || []
    if selected_tag_ids.empty? || selected_tag_ids.size == Tag.count
      order("RANDOM()").first
    else
      joins(:tags)
        .group('songs.id')
        .select('songs.*, COUNT(tags.id) as tag_count')
        .having('COUNT(tags.id) = ?', selected_tag_ids.size)
        .where(tags: { id: selected_tag_ids })
        .where('songs.id NOT IN (?)', joins(:tags).where.not(tags: { id: selected_tag_ids }).select(:id))
        .first ||
        joins(:song_tags)
        .where(song_tags: { tag_id: selected_tag_ids })
        .group('songs.id')
        .select('songs.*, COUNT(song_tags.tag_id) as tag_count')
        .order('tag_count DESC, RANDOM()')
        .first
    end
  end

  def self.fetch_spotify_song(title, search_term="aespa")
    track = RSpotify::Track.search("#{title} #{search_term}").first
    {
      title: track.name,
      album_art: track.album.images.first['url'],
      id: track.id
    }
  end
end

app/controllers/aespa/base_controller.rb
class Aespa::BaseController < ApplicationController
  before_action :aespa_theme_color
  before_action :set_video_url

  private

  def aespa_theme_color
    @theme_color = "aespa"
  end
  def set_video_url
    unless cookies[:aespa_video_url]
      s3_service = S3Service.new
      cookies[:aespa_video_url] = { value: s3_service.fetch_video_url('umbrellas/va2.mp4'), expires: 6.days.from_now }
    end
  end
end

app/controllers/aespa/songs_controller.rb
class Aespa::SongsController < Aespa::BaseController
  skip_before_action :set_video_url, only: :show
  skip_before_action :set_ogp, only: :show

  def index; end

  def aespa_no_1
      @song = Song.select_song(params[:tag_titles])
      redirect_to aespa_song_path(@song.title)
  end

  def show
    @song = Song.find_by_title(params[:title])
    search_term = @song.title == "'Till We Meet Again" ? "spicy aespa" : "aespa"
    @spotify_song = Song.fetch_spotify_song(@song.title, search_term)

    set_meta_tags twitter: {
      card: "summary",
      url: CGI.escape(request.original_url),
      title: "A.I.SongSearcher",
      image: @spotify_song[:album_art],
      description: "AIが私に選んだおすすめの楽曲は、aespaの#{@spotify_song[:title]}"
    }
  end
end

app/helpers/aespa/base_helper.rb
module Aespa::BaseHelper
end

app/helpers/aespa/songs_helper.rb
module Aespa::SongsHelper
end

app/views/aespa/songs/aespa_no_1.html.erb
<div class="min-h-screen">
  <div class="m-5 p-5 sm:m-10 sm:p-10 border-2 flex-initial grid grid-cols-2 gap-4">
    <div class="text-2xl sm:text-6xl col-span-2">
      今の貴方におすすめの曲は、aespaの<%= @spotify_song[:title] %>です。
    </div>
    <div class="col-span-2">
      <iframe style="border-radius:12px"
        src="https://open.spotify.com/embed/track/<%= @spotify_song[:id] %>"
        width="100%" height="352"
        frameBorder="0"
        allowfullscreen=""
        allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
        loading="lazy"></iframe>
    </div>
    <div class="col-span-2">
      <%= link_to "https://twitter.com/share?url=#{request.base_url}/#{@spotify_song[:id]}&text=AIが私に選んだおすすめの楽曲は、aespaの#{@spotify_song[:title]}です！&hashtags=A.I.SongSearcher", target: '_blank', class: 'mx-4 twitter-share-button', data: {show_count: 'false'} do %>
        <div class="flex">
          <svg xmlns="http://www.w3.org/2000/svg" class="mx-2 fill-current w-16 h-16" viewBox="0 0 24 24">
            <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
          </svg>
          <div class="text-xl sm:text-4xl">Twitter Share</div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/aespa/songs/show.html.erb
<div class="min-h-screen">
  <div class="m-5 p-5 sm:m-10 sm:p-10 border-2 flex-initial grid grid-cols-2 gap-4">
    <div class="text-2xl sm:text-6xl col-span-2">
      今の貴方におすすめの曲は、aespaの<%= @spotify_song[:title] %>です。
    </div>
    <div class="col-span-2">
      <iframe style="border-radius:12px"
        src="https://open.spotify.com/embed/track/<%= @spotify_song[:id] %>"
        width="100%" height="352"
        frameBorder="0"
        allowfullscreen=""
        allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
        loading="lazy"></iframe>
    </div>
    <div class="col-span-2">
      <%= link_to "https://twitter.com/share?url=#{CGI.escape(request.original_url)}&text=AIが私に選んだおすすめの楽曲は、aespaの#{@spotify_song[:title]}です！&hashtags=AISongSearcher", target: '_blank', class: 'mx-4 twitter-share-button', data: {show_count: 'false'} do %>
        <div class="flex">
          <svg xmlns="http://www.w3.org/2000/svg" class="mx-2 fill-current w-16 h-16" viewBox="0 0 24 24">
            <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
          </svg>
          <div class="text-xl sm:text-4xl">Twitter Share</div>
        </div>
        <%= link_to "A.I.Song Searcherに戻る",aespa_songs_path, class: "btn btn-ghost normal-case text-xl m-4", data: { turbo: false } %>
      <% end %>
    </div>
  </div>
</div>