config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  get 'terms', to: 'tops#terms'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'treatment', to: 'tops#treatment'

  get 'post', to: 'tops#post'

  get 'saikyouni_omoroi_app', to:'tops#saikyouni_omoroi_app'

  get 'prison', to: 'calorie_counter/chats#prison'
  get 'purgatory', to: 'calorie_counter/chats#purgatory'
  get '/path/to/mercy', to: 'calorie_counter/chats#mercy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'

  post 'select_theme', to: 'themes#select'

  namespace :calorie_counter do
    resources :chats
  end

  namespace :pomodoro_timer do
    resources :timers
  end

  namespace :stolen_umbrella do
    resources :umbrellas
  end

  namespace :talk_deck_butler do
    resources :tasks
  end

  get 'escape', to: 'escape/homes#top'
  namespace :escape do
    resources :homes
    resources :sns
    resources :rooms
    resources :endroles
  end

  namespace :aespa do
    resources :songs, only: [:index, :show], param: :title do
      collection do
        get 'aespa_no_1'
      end
    end
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page_view.rb
class PageView < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :song_tags, dependent: :destroy
  has_many :tags, through: :song_tags

  validates :title, presence: true
  validates :body, presence: true

  def self.select_song(tag_titles)
    selected_tag_ids = Tag.where(title: tag_titles).pluck(:id) || []
    if selected_tag_ids.empty? || selected_tag_ids.size == Tag.count
      order("RANDOM()").first
    else
      joins(:tags)
        .group('songs.id')
        .select('songs.*, COUNT(tags.id) as tag_count')
        .having('COUNT(tags.id) = ?', selected_tag_ids.size)
        .where(tags: { id: selected_tag_ids })
        .where('songs.id NOT IN (?)', joins(:tags).where.not(tags: { id: selected_tag_ids }).select(:id))
        .first ||
        joins(:song_tags)
        .where(song_tags: { tag_id: selected_tag_ids })
        .group('songs.id')
        .select('songs.*, COUNT(song_tags.tag_id) as tag_count')
        .order('tag_count DESC, RANDOM()')
        .first
    end
  end

  def self.fetch_spotify_song(title, search_term="aespa")
    track = RSpotify::Track.search("#{title} #{search_term}").first
    {
      title: track.name,
      album_art: track.album.images.first['url'],
      id: track.id
    }
  end
end

app/models/song_tag.rb
class SongTag < ApplicationRecord
  belongs_to :song, dependent: :destroy
  belongs_to :tag, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :songs, through: :song_tags
  has_many :song_tags, dependent: :destroy

  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/umbrella.rb
class Umbrella < ApplicationRecord
  validates :memory, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :tasks, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  enum role: { general: 0, prisoner: 1, admin:2}



  def self.create_prisoner
    user = create(email: "prisoner-#{SecureRandom.hex(8)}@example.com", password: "1234", password_confirmation: "1234", role: :prisoner)
    Rails.logger.info user.errors.full_messages if user.errors.any?
    user
  end

  def prisoner?
    role == "prisoner"
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  rescue_from RuntimeError, with: :handle_unwanted_word
  before_action :prisoner_go_to_prison , only: [:index]
  before_action :not_prison, only: [:purgatory]
  
  def index
    random_number = rand(1..10)
    input = WordChecker.check_input(params[:input])
    if random_number != 1
      client = OpenAiClient.new
    else
      client = OpenAiClientDevil.new
    end
    @response = client.chat(input)
  end
  
  def prison
    user = User.create_prisoner
    auto_login(user)
  end

  def purgatory; end

  def mercy
    current_user.destroy  if current_user.prisoner?
    redirect_to root_path
  end

  private

  def handle_unwanted_word(e)
    if e.message == "Input contains unwanted word"
      redirect_to prison_path
    else
      raise e
    end
  end
end

app/controllers/escape/base_controller.rb
class Escape::BaseController < ApplicationController
  before_action :escape_theme_color
  layout "game_layout"

  private

  def escape_theme_color
    @theme_color = "aespa"
  end

end

app/controllers/escape/endroles_controller.rb
class Escape::EndrolesController < Escape::BaseController
end

app/controllers/escape/homes_controller.rb
class Escape::HomesController < Escape::BaseController
  def top; end

  def index
    s3_service = S3Service.new
    @video_url = s3_service.fetch_video_url('umbrellas/glitch_-_27706 (1080p).mp4')
  end
end

app/controllers/escape/rooms_controller.rb
class Escape::RoomsController < Escape::BaseController
end

app/controllers/escape/sns_controller.rb
class Escape::SnsController < Escape::BaseController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
   end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to plots_path, success: "ログインしました。"
    else
      flash.now[:danger] = "ログインできませんでした。"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_path, status: :see_other, success: "ログアウトしました。"
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def select
    theme = ThemeChecker.check_theme(params[:selectedTheme])
    if theme
      cookies.permanent[:selectedTheme] = theme
      redirect_to request.referer
    else
      redirect_to root_path
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :theme_color
  skip_before_action :set_ogp, only: :top

  def top
    @color_select = "approval"
    page_view = PageView.first
    page_view.increment!(:count)
    set_meta_tags twitter: {
      card: "summary_large_image",
      url: "https://kuso-app-institute.magia.runteq.jp/",
      title: "K.U.S.O.AppInstitute",
      image: "https://kuso-app-institute.magia.runteq.jp/images/ogp2.png",
      description: "クソアプリ研究所を発見したよ！"
    }
  end

  def terms; end

  def privacy_policy; end

  def treatment; end

  def saikyouni_omoroi_app
    @theme_color = "cupcake"
  end

  private
  def theme_color
    @theme_color = cookies.permanent[:selectedTheme]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to plots_path, success: "アカウントを作成しました🎉"
    else
      flash.now[:danger] = "アカウトを作成できませんでした。"
      render :new
    end
  end

  def my_page
    @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "アカウントを削除しました。"
  end

  private

  def user_params
    params.permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_gpt_helper.rb
module ChatGptHelper
end

app/helpers/escape/base_helper.rb
module Escape::BaseHelper
end

app/helpers/escape/endroles_helper.rb
module Escape::EndrolesHelper
end

app/helpers/escape/homes_helper.rb
module Escape::HomesHelper
end

app/helpers/escape/rooms_helper.rb
module Escape::RoomsHelper
end

app/helpers/escape/sns_helper.rb
module Escape::SnsHelper
end

app/helpers/omoroiapps_helper.rb
module OmoroiappsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/escape/homes/index.html.erb
<div class="relative min-h-screen overflow-hidden">
  <div class="z-20">
    <div class="mockup-window border bg-base-300 h-screen w-screen">
      <div data-controller="media" class="justify-center text-7xl bg-base-200 flex-col">
        <video muted class="z-50 w-full h-full object-cover absolute" data-media-target="video">
          <source src="<%= @video_url %>" type="video/mp4">
        </video>
        <audio src="<%= asset_path 'bg.mp3' %>" preload="auto" data-media-target="audio"></audio>
        <audio src="<%= asset_path 'yume.mp3' %>" preload="auto" data-media-target="yume"></audio>
        <div data-media-target="back" class="z-20 hidden"><%= image_tag "macbook.jpg", class: "w-full h-full object-cover absolute" %></#div>
        <div class="hidden absolute bottom-0 flex w-screen" data-media-target="chats">
          <div class="bottom-5 z-40 mx-5 flex-1 relative">
            <div class="h-32 heropattern-floatingcogs-sky-600 opacity-25">
            </div>
            <div class="h-32 rounded-lg border-2 border-sky-900 bg-gradient-to-b from-sky-700 absolute top-0 left-0 right-0 bottom-0 animate-scale-up-hor-center">
              <div class="text-sky-100 border-b border-sky-900 px-4 text-2xl">ハル</div>
              <div data-typing-target="play" class="px-4 pt-2 text-sky-100 text-2xl">…………眠ってしまっていた。</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/escape/homes/top.html.erb
<div class="relative min-h-screen overflow-hidden font-robo" data-controller="home-mac">
  <%= image_tag "macbook.jpg", class: "animate-kenburns-top md:block w-full h-full object-cover md:w-full md:h-auto absolute" %>
  <div data-controller="typing">
    <div data-home-mac-target="HelloElement" class="hidden z-20 animate-scale-up-hor-center">
      <div class="mockup-window border bg-base-300 h-screen w-screen">
        <div class="flex justify-center px-4 text-7xl py-16 bg-base-200 flex-col">
          <div data-typing-target="welcome" class="text-9xl"></div>
          <div data-typing-target="escape" class="text-9xl"></div>
          <div data-typing-target="object" class="text-3xl m-5"></div>
        </div>
      </div>
    </div>
    <div class="hidden absolute bottom-0 flex w-screen" data-home-mac-target="LoginElement">
      <div class="flex-1 mx-5 ml-10 my-10 bottom-0 z-50 animate-scale-up-hor-center">
        <div class="mockup-window border bg-base-300">
          <%= link_to escape_homes_path  do %>
            <div data-typing-target="play" class="flex justify-center px-4 text-7xl py-16 bg-base-200">
            </div>
          <% end %>
        </div>
      </div>
      <div class="flex-1 mx-5 my-10 z-50 animate-scale-up-hor-center">
        <div class="mockup-window border bg-base-300">
          <%= link_to root_path, data: { turbo: false } do%>
            <div data-typing-target="return" class="flex justify-center px-4 text-7xl py-16 bg-base-200">
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>