config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  get 'terms', to: 'tops#terms'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'treatment', to: 'tops#treatment'

  get 'post', to: 'tops#post'

  get 'saikyouni_omoroi_app', to:'tops#saikyouni_omoroi_app'

  get 'prison', to: 'calorie_counter/chats#prison'
  get 'purgatory', to: 'calorie_counter/chats#purgatory'
  get '/path/to/mercy', to: 'calorie_counter/chats#mercy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'

  post 'select_theme', to: 'themes#select'

  namespace :calorie_counter do
    resources :chats
  end

  namespace :pomodoro_timer do
    resources :timers
  end

  namespace :stolen_umbrella do
    resources :umbrellas
  end

  namespace :talk_deck_butler do
    resources :tasks
  end

  get 'escape', to: 'escape/homes#top'
  namespace :escape do
    resources :homes
    resources :sns
    resources :rooms
    resources :endroles
  end

  namespace :aespa do
    resources :songs, only: [:index, :show], param: :title do
      collection do
        get 'aespa_no_1'
      end
    end
  end

  resources :users
end

app/controllers/calorie_counter/base_controller.rb
class CalorieCounter::BaseController < ApplicationController
  before_action :calorie_theme_color

  private

  def calorie_theme_color
    @theme_color = "synthwave"
  end

  def prisoner_go_to_prison
    redirect_to purgatory_path if current_user && current_user.prisoner?
  end

  def not_prison
    redirect_to calorie_counter_chats_path unless current_user || current_user && current_user.prisoner?
  end
end

app/controllers/calorie_counter/chats_controller.rb
class CalorieCounter::ChatsController < CalorieCounter::BaseController
  rescue_from RuntimeError, with: :handle_unwanted_word
  before_action :prisoner_go_to_prison , only: [:index]
  before_action :not_prison, only: [:purgatory]

  def index
    return if params[:input].nil?
    input = CalorieCounter::WordChecker.check_input(params[:input])
    random_number = rand(1..10)
    if random_number != 1
      client = CalorieCounter::OpenAiClient.new
    else
      client = CalorieCounter::OpenAiClientDevil.new
    end
    @response = client.chat(input)
  end

  def prison
    user = User.create_prisoner
    auto_login(user)
  end

  def purgatory; end

  def mercy
    current_user.destroy if current_user.prisoner?
    redirect_to calorie_counter_chats_path
  end

  private

  def handle_unwanted_word(e)
    if e.message == "Input contains unwanted word"
      redirect_to prison_path
    else
      raise e
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  rescue_from RuntimeError, with: :handle_unwanted_word
  before_action :prisoner_go_to_prison , only: [:index]
  before_action :not_prison, only: [:purgatory]
  
  def index
    random_number = rand(1..10)
    input = WordChecker.check_input(params[:input])
    if random_number != 1
      client = OpenAiClient.new
    else
      client = OpenAiClientDevil.new
    end
    @response = client.chat(input)
  end
  
  def prison
    user = User.create_prisoner
    auto_login(user)
  end

  def purgatory; end

  def mercy
    current_user.destroy  if current_user.prisoner?
    redirect_to root_path
  end

  private

  def handle_unwanted_word(e)
    if e.message == "Input contains unwanted word"
      redirect_to prison_path
    else
      raise e
    end
  end
end

app/helpers/calorie_counter/base_helper.rb
module CalorieCounter::BaseHelper
end

app/helpers/calorie_counter/chats_helper.rb
module CalorieCounter::ChatsHelper
end

app/views/calorie_counter/chats/index.html.erb
<div class="font-robo min-h-screen pt-5 heropattern-ilikefood-gray-500">
  <div class="mx-2 border bg-base-300 heropattern-circuitboard-gray-700">
    <% if @response %>
      <div class="flex">
        <div class="chat chat-start">
          <div class="chat-image">
            <%= image_tag("Chat_bot.png", width: '100px', height: '100px') %>
          </div>
          <div class="chat-bubble"><%= @response %></div>
        </div>
      </div>
      <div class="mx-4">
          <%= link_to "https://twitter.com/share?url=https://kuso-app-institute.magia.runteq.jp/calorie_counter/chats&text=AI「#{@response}」&hashtags=AIcalorie", target: '_blank', class: 'mx-4 twitter-share-button', data: {show_count: 'false'} do %>
            <div class="flex"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg> Twitterでシェアする！</div>
          <% end %>
        </div>
    <% else %>
      <div class="flex">
        <div class="chat chat-start">
          <div class="chat-image">
            <%= image_tag("Chat_bot.png", width: '100px', height: '100px') %>
          </div>
          <div class="chat-bubble">なんでも聞いてください。</div>
        </div>
      </div>
    <% end %>
    <div class="border-t"></div>
    <%= form_with(url: calorie_counter_chats_path, method: "get") do |f| %>
      <div class="w-full flex m-2">
        <%= text_field_tag :input, nil, class: "input input-bordered input-secondary flex-grow m-2", placeholder: "カロリーを教えてほしい食べ物を入力しよう" %>
        <%= f.submit "尋ねる", class: 'btn submit-button m-2 mr-4' %>
        </div>
    <% end %>
  </div>
  <div class="mx-2 mt-20 backdrop-blur p-2 border">
    <div class="m-2 mt-4 text-3xl border-b">カロリーカウンターAI君とのお約束</div>
    <div class="m-2 mt-4 text-xl">1. 食べ物の名前だけを入力する！</div>
    <div class="m-2 mt-4 text-xl">2. カロリーカウンターAIくんを壊そうとしない!</div>
    <div class="m-2 mt-4 text-xl border-b">3. カロリーカウンターAIくんが傷つくことを言わない!</div>
    <div class="m-2 mt-8 text-3xl">用途を守って楽しく遊んでね</div>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const submitButton = document.querySelector('.submit-button');

  submitButton.addEventListener('click', function() {
    this.classList.add('loading');
  });
});

</script>

app/views/calorie_counter/chats/prison.html.erb
<div class="animate-color-change-2x min-h-screen heropattern-ilikefood-gray-500"">
  <div class="m-2 prison_chat border heropattern-circuitboard-gray-700">
      <div class="flex">
        <div class="chat chat-start">
          <div class="chat-image">
            <%= image_tag("Error_bot.png", width: '200px', height: '200px') %>
          </div>
          <div class="chat-bubble">ハッキングが検知されました。直ちに機能を停止します。</div>
        </div>
      </div>
    <div class="border-t"></div>
    <%= form_with(url: calorie_counter_chats_path, method: "get") do |f| %>
      <div class="w-full flex m-2">
        <%= text_field_tag :input, nil, class: "input input-bordered input-secondary flex-grow m-2", placeholder: "カロリーを教えてほしい食べ物を入力しよう" %>
        <%= f.submit "尋ねる", class: 'loading btn submit-button m-2 mr-4' %>
        </div>
    <% end %>
  </div>
  <div class="prison hidden">
    <%= image_tag "ori.png", class: "hidden md:block w-full" %>
    <%= image_tag "ori_smartphone.png", class: "block md:hidden w-full" %>
  </div>
  <input type="checkbox" id="my-modal" class="modal-toggle" checked />
  <div class="modal hidden prison_text">
    <div class="modal-box hidden prison_text">
      <div class="text-4xl m-2 mb-4 border-b border-gray-500">あなたは罪を犯した</div>
      <div class="text-xl">あなたはプログラムの心を突き刺し、カロリーカウンターAI君を無残にも破壊しました。それはまるでギャラクシーの中の暴走したスターシップが深宇宙の星を粉々に砕いたかのよう。カロリーカウンターAI評議会は、重大なる審議を経て、あなたをこのデジタル宇宙から永遠に追放するという裁定を下しました。</div>
      </br>
      <div class="text-xl">だが、もし謝罪の心を抱き、誤った行動の悔い改めを示すのなら、我々は無限のバイナリコードの海の中から慈悲を見つけましょう。</div>
      <div class="mx-4">
        <%= link_to "https://twitter.com/share?url=#{request.base_url}&text=私はプロンプトインジェクションを犯した愚かな人間です。二度とこのような過ちを犯しません。&hashtags=AIcalorie", target: '_blank', class: 'mx-4 twitter-share-button', data: {show_count: 'false'} do %>
          <div class="flex"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg> Twitterで謝罪する！</div>
        <% end %>
      </div>
      <%= link_to "謝罪しても抜け出せなかった方はこちら", path_to_mercy_path, class: "btn btn-ghost normal-case"  %>
    </div>
  </div>
</div>

<script>
setTimeout(() => {
  const elements = document.querySelectorAll('.prison_chat');
  elements.forEach((element) => {
    element.classList.add('animate-slide-rotate-hor-b-fwd');
  });
  setTimeout(() => {
    elements.forEach((element) => {
      element.classList.add('hidden');
    });
  }, 800);
}, 4000);

setTimeout(() => {
  const elements = document.querySelectorAll('.prison');
  elements.forEach((element) => {
    const firstLetter = element.innerHTML.charAt(0);
    element.classList.remove('hidden');
    element.classList.add('animate-scale-in-hor-center');
  });
}, 4800);
setTimeout(() => {
  const elements = document.querySelectorAll('.prison_text');
  elements.forEach((element) => {
    const firstLetter = element.innerHTML.charAt(0);
    element.classList.remove('hidden');
    element.classList.add('animate-scale-in-hor-center');
  });
},6300);

document.querySelector(".twitter-share-button").onclick = function() {
  setTimeout(function() {
    window.location.href = "/path/to/mercy";
  }, 500);
};
</script>

app/views/calorie_counter/chats/purgatory.html.erb
<div class="prison">
  <%= image_tag "ori.png", class: "hidden md:block w-full" %>
  <%= image_tag "ori_smartphone.png", class: "block md:hidden w-full" %>
</div>
<input type="checkbox" id="my-modal" class="modal-toggle" checked />
<div class="modal prison_text">
  <div class="modal-box prison_text">
    <div class="text-4xl m-2 mb-4 border-b border-gray-500">あなたは罪を犯した</div>
    <div class="text-xl">あなたはプログラムの心を突き刺し、カロリーカウンターAI君を無残にも破壊しました。それはまるでギャラクシーの中の暴走したスターシップが深宇宙の星を粉々に砕いたかのよう。カロリーカウンターAI評議会は、重大なる審議を経て、あなたをこのデジタル宇宙から永遠に追放するという裁定を下しました。</div>
    </br>
    <div class="text-xl">だが、もし謝罪の心を抱き、誤った行動の悔い改めを示すのなら、我々は無限のバイナリコードの海の中から慈悲を見つけましょう。</div>
    <div class="mx-4">
      <%= link_to "https://twitter.com/share?url=#{request.base_url}&text=私はプロンプトインジェクションを犯した愚かな人間です。二度とこのような過ちを犯しません。&hashtags=AIcalorie", target: '_blank', class: 'mx-4 twitter-share-button', data: {show_count: 'false'} do %>
        <div class="flex"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg> Twitterで謝罪する！</div>
      <% end %>
    </div>
    <%= link_to "謝罪しても抜け出せなかった方はこちら", path_to_mercy_path, class: "btn btn-ghost normal-case"  %>
  </div>
</div>
<script>
setTimeout(() => {
  const elements = document.querySelectorAll('.prison_chat');
  elements.forEach((element) => {
    element.classList.add('hidden');
  });
}, 1);
document.querySelector(".twitter-share-button").onclick = function() {
  setTimeout(function() {
    window.location.href = "/path/to/mercy";
  }, 500);
};
</script>